In [7]:
# Imports of Fun

# These two are to create the directory and filenames of the charts
from pathlib import Path

# This is to specify the location of my modules
import sys as syeet
syeet.path.append(str(Path().cwd())+"/"+"Modules")

# This is to specify the location of the .dat files for this assignment, Github did not like these files so I had to store them somewhere else
datapath = str(Path().cwd()).replace("Aerospace-Computing","Misc/")

# Numpy and PyPlot
import numpy as np
import matplotlib.pyplot as plt
#import sympy as sp
import scipy as spy
import pandas as pd

# My library
import kavouras1 as k
import textbook as t

# Inline outputs of matplotlib
%matplotlib inline

# Sympy symbols
#x,y = sp.symbols('x y')

In [8]:
A = np.array([[5,3,0,0,0],[0,5,0,0,0],[0,0,5,0,0],[0,0,0,5,1],[0,0,0,0,5]])
B = np.array([[51,2,3,5,7,11],[1,52,3,5,7,11],[1,2,53,5,7,11],[1,2,3,55,7,11],[1,2,3,5,57,11],[1,2,3,5,7,61]])

In [9]:
print("Eingenvalues")
print(np.linalg.eig(A)[0])
print(" ")
print("Eigenvectors")
print(np.around(np.linalg.eig(A)[1],10))

Eingenvalues
[5. 5. 5. 5. 5.]
 
Eigenvectors
[[ 1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.]]


In [10]:
print("Eingenvalues")
print(np.around(np.linalg.eig(B)[0],10))
print(" ")
print("Eigenvectors")
print(np.around(np.linalg.eig(B)[1],10))

Eingenvalues
[50.+0.j 79.+0.j 50.+0.j 50.+0.j 50.+0.j 50.-0.j]
 
Eigenvectors
[[-0.9968264 +0.j          0.40824829+0.j          0.05272661+0.j
  -0.0818284 +0.j         -0.13454598+0.01126109j -0.13454598-0.01126109j]
 [ 0.03560094+0.j          0.40824829+0.j          0.52287692+0.j
   0.53328458+0.j          0.63461232+0.j          0.63461232-0.j        ]
 [ 0.03560094+0.j          0.40824829+0.j         -0.57073534+0.j
   0.69042454+0.j          0.26677967+0.05453084j  0.26677967-0.05453084j]
 [ 0.03560094+0.j          0.40824829+0.j         -0.5693517 +0.j
  -0.47909535+0.j          0.43547624+0.04726278j  0.43547624-0.04726278j]
 [ 0.03560094+0.j          0.40824829+0.j          0.19224912+0.j
  -0.03669653+0.j         -0.21166832+0.36970749j -0.21166832-0.36970749j]
 [ 0.03560094+0.j          0.40824829+0.j          0.19224912+0.j
  -0.03669653+0.j         -0.23915642-0.27264727j -0.23915642+0.27264727j]]


In [11]:
vals = np.array([[0,0]])
eigB = np.array([])
l = 0
for eigs in np.linalg.eig(B)[0]:
    eigB = np.append(eigB,np.around(eigs,5))
for i in eigB:
    if len(vals) > 1:
        iter = 1
        for k in vals:
            if i == k[0]:
                k[1] += 1
                break
            elif iter == len(vals):
                vals = np.vstack((vals,[i,1]))
            iter += 1
    else:
        vals = np.vstack((vals,[i,1]))
ind = 0
stored = 0
for j in vals:
    if j[1] > stored:
        stored = ind
    ind += 1

In [12]:
eigenvals, eigenvects = np.linalg.eig(B)
idx = np.where(np.isclose(eigenvals,vals[stored,0]))[0][0]

C = B - eigenvals[idx]*np.identity(B.shape[0])
v1 = eigenvects[:,idx]
#v2 = np.linalg.solve(C,v1)

v1 = v1/np.linalg.norm(v1)
#v2 = v2/np.linalg.norm(v2)

print("Eigenvector 1:")
print(v1)
print("Eigenvector 2:")
#print(v2)

Eigenvector 1:
[-0.9968264 +0.j  0.03560094+0.j  0.03560094+0.j  0.03560094+0.j
  0.03560094+0.j  0.03560094+0.j]
Eigenvector 2:
