In [48]:
# Imports of Fun

# These two are to create the directory and filenames of the charts
from pathlib import Path

# This is to specify the location of my modules
import sys as syeet
syeet.path.append(str(Path().cwd())+"/"+"Modules")

# Time
import time
import math

# Numpy and PyPlot
import numpy as np
import matplotlib.pyplot as plt

# My library
import kavouras1 as k
import textbook as t

# Inline outputs of matplotlib
%matplotlib inline

In [49]:
# Question 2
# Part A+B
# M#: M13852536

Marray = np.array([8, 5, 2, 5, 3, 6])
Marray2 = np.vstack((Marray,np.random.randint(-10,10,(5,6))))
numb = np.prod(np.diagonal(Marray2))
while numb == 0:
    Marray2 = np.vstack((Marray,np.random.randint(-10,10,(5,6))))
    numb = np.prod(np.diagonal(Marray2))
print(Marray2)
print("Determinant = "+str(numb))

[[ 8  5  2  5  3  6]
 [ 0 -8  1  1 -7 -9]
 [ 3  4  5 -2 -5  4]
 [-6 -6 -6  1 -2  3]
 [-9  8 -1  2 -5  3]
 [-7  5 -1 -6 -9  7]]
Determinant = 11200


This creates a 6x6 matrix that uses my M number as the first row, and random values as the second row. Then, it gets the determinant, and if this value doesn't equal zero, the matrix is non-singular. if this value does equal zero, the matrix is singular and it regenerates the random values.

In [50]:
# Part C
Barray = np.dot(Marray2,np.array([[2],[2],[2],[2],[2],[2]]))
print(Barray)


[[ 58]
 [-44]
 [ 18]
 [-32]
 [ -4]
 [-22]]


In [51]:
# Part D
x = np.linalg.solve(Marray2,Barray)
print(x)

[[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]


In [52]:
# Part E
residual = np.dot(Marray2,x) - Barray
norm = np.linalg.norm(residual)
print("Unrounded Norm:")
print(norm)
norm = np.around(norm,decimals=2)
print("Rounded Norm:")
print(norm)


Unrounded Norm:
1.0048591735576161e-14
Rounded Norm:
0.0


If the norm of the residual is zero, that means the difference between the inital B vector and the computed B vector with the solution vector is zero. Because the norm is very, very close to zero, it can be assumed there is no difference between the initial and calculated B vector, and the solution vector is correct.